# Generated by Django 4.0 on 2024-12-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('comment', models.TextField()),
            ],
        ),
    ]
